apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: MTIzNDU2Nzg=
  MYSQL_ROOT_PASSWORD: MTIzNDU2Nzg=
  MYSQL_DATABASE: cGhvbmVib29r
  MYSQL_DATABASE_HOST: ZGItc2VydmljZQ==